spring:
  profiles:
    active: mysql
  batch:
    job:
      names: ${job.name:NONE}

jasypt:
  encryptor:
    bean: jasyptStringEncryptor


klaytn:
  header:
    authorization: ENC(mjs/ddG+OgZymEnzob/ooBZy+K/BxCth+Qa5R6hgNxZi13lCt27lhWKMEBOvaRBvkMpav5XCZP8b0H1e8C88JbkAH/QmrwBpO/Ck27lTt2svHNuSejY+RfneKpC4ZyF5i8JC+p13uVg=)
    x-krn : ENC(XVvupuWVowMTmvagGh3ZBBYchJ4DWc6+s/GFpUNgSYJ+Y5+BiiFp6kaRLTgJ6ZCtAnsU7UldqQMOgiqIKuwi0i/iOl+DFMm5eXkh6uUJE22sybLR3xeuFw==)
    x-chain-id : 1001
    Content-Type : application/json

  wallet:
    tx:
      from:
        address: ENC(OWTcYU660JxULT7hyzIcpwcK8lqGmdg9jU4dLwyH+hyExHl1LfXLY7jO5LJ1Ue55K1HRiuRX6bo=)



---

spring:
  h2:
    console:
      enabled: true
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      username: sa
      password:
      jdbc-url: jdbc:h2:tcp://localhost/~/test;
      connection-test-query: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  batch:
    initialize-schema: always
    job:
      enabled: false
  config:
    activate:
      on-profile: local


---

spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: hgs
      password: hgs1
      jdbc-url: jdbc:mysql://localhost:3306/batch
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  batch:
    job:
      enabled: false
  config:
    activate:
      on-profile: mysql

logging:
  level:
    com.batchschedulerbasic: debug
